# Generated by Django 3.1.2 on 2020-12-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('recipe',)},
        ),
    ]
