# Generated by Django 3.1.2 on 2020-12-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201221_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.recipes'),
        ),
    ]
