# Generated by Django 3.1.2 on 2021-01-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userfood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFood',
        ),
    ]
