# Generated by Django 3.1.2 on 2021-01-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210107_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookfood',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.userorders'),
        ),
        migrations.AlterField(
            model_name='userfood',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.userorders'),
        ),
        migrations.AlterField(
            model_name='userorders',
            name='order_finish',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='userorders',
            name='order_send',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='userorders',
            name='order_start',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
