# Generated by Django 3.1.2 on 2021-01-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210107_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookfood',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfood',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userorders',
            name='order_finish',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userorders',
            name='order_send',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userorders',
            name='order_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
